### ISSUE TITLE
Using absolute vs relative paths

### ISSUE THREAD

**Issue by sandervandorsten** [casperdamen123/python_projects_DiP#1]
(This is not a big problem but I'm just nitpicking for learning purposes of you getting a code review + having to resolve a github issue)

Hi Casper,

I've reviewed your code in `iris.ipynb` Structure and code look good and understandable! I have a small suggestion.

for accessing your data you use an absolute path by calling `os.cwd()` and `os.chdir(...)` to navigate to that path. This works fine on your computer, but now lets imagine I'm a collegae and I `git clone` your repository to work on the code a bit on my computer. I'd have to fix this to make it work on mine.

Could you update your code so it works with relative paths instead of absolute paths? you may only assume that I have the same folder structure as you in this repository (because I would `clone` the repository).

Let me know if you agree with the proposed changes. We can close the issue once it has been changed; or we've come to a different agreement. Thanks!

**Comment by CICDamen** [comment]
Hi Sander,

Thanks for reviewing!

I agree with the proposed change and have added the relative path for `iris.ipynb`. To be consistent, I've also added this relative path to the other notebooks when setting the working directory.

Let me know if the change aligns with your thinking!

**Comment by sandervandorsten** [comment]
Hi Casper,

Hoe proactive of you! However, I'd suggest to not change the working directory, but the relative importing of your data file. This leads to less possible side effects later in the code. E.g.:

```
from pathlib import Path
iris_data_path = Path("../data/iris.csv")
pd.read_csv(iris_data_path)
```

**Comment by CICDamen** [comment]
Hi Sander,

Check! I've updated the notebooks accordingly.

Kind regards,
Casper
